//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.EMPLOYEE = new HashSet<EMPLOYEE>();
            this.PROJECT = new HashSet<PROJECT>();
        }
    
        public string DEPTNO { get; set; }
        public string DEPTNAME { get; set; }
        public string MGRNO { get; set; }
        public string ADMRDEPT { get; set; }
        public string LOCATION { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual ICollection<PROJECT> PROJECT { get; set; }
    }
}
