//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_ACT
    {
        public int ID { get; set; }
        public string EMPNO { get; set; }
        public string PROJNO { get; set; }
        public short ACTNO { get; set; }
        public Nullable<decimal> EMPTIME { get; set; }
        public Nullable<System.DateTime> EMSTDATE { get; set; }
        public Nullable<System.DateTime> EMENDATE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
