//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.EMP_ACT = new HashSet<EMP_ACT>();
        }
    
        public string EMPNO { get; set; }
        public string FIRSTNME { get; set; }
        public string MIDINIT { get; set; }
        public string LASTNAME { get; set; }
        public string WORKDEPT { get; set; }
        public string PHONENO { get; set; }
        public Nullable<System.DateTime> HIREDATE { get; set; }
        public string JOB { get; set; }
        public short EDLEVEL { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> BONUS { get; set; }
        public Nullable<decimal> COMM { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<EMP_ACT> EMP_ACT { get; set; }
    }
}
