//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public PROJECT()
        {
            this.EMP_ACT = new HashSet<EMP_ACT>();
        }
    
        public string PROJNO { get; set; }
        public string PROJNAME { get; set; }
        public string DEPTNO { get; set; }
        public string RESPEMP { get; set; }
        public Nullable<decimal> PRSTAFF { get; set; }
        public Nullable<System.DateTime> PRSTDATE { get; set; }
        public Nullable<System.DateTime> PRENDATE { get; set; }
        public string MAJPROJ { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<EMP_ACT> EMP_ACT { get; set; }
    }
}
